#####################
# Part01 Parameters #
#####################

# species with "high quality" annotations
template_species_list = ["Bcur", "Bdor", "Bole", "Ccap"]

# full species list
full_species_list = ['Bcur', 'Bdor', 'Bole', 'Ccap', 'Bcor', 'Blat', 'Bzon', 'Afra', 'Bmin', 'Bjar', 'Aobl', 'Asus', 'Btry']

# number of n's used to create alignment boarders
n_count = 50

# cds gap filter parameters
max_gap_percent = 0
max_gap_length = 0

# exon length filter parameters
min_exon_length = 100

# tapir options string
tapir_opts_string = "--intervals=2-3,3-5,5-8,8-10,10-18 --times=2,3,5,8,10,17 --tree-format=newick"

################################################### Paths #############################################################

# As a rule, variables with "path" in the name are relitive paths to a directory and end in a '/'.
# Variables with "fn" for "file name" are the relitive path to a file and end with the file's name.


################
# Part01 Paths #
################

# input
groups_fn =                         "../data/part01/input/filtered_orthomcl_output_6181genes.txt"
gff_path =                          "../data/part01/input/gff/"
fasta_path =                        "../data/part01/input/fasta/"

# intermediate
db_path =                           "../data/part01/intermediate/gff_databases/"
json_path =                         "../data/part01/intermediate/json/"
template_alignment_path =           "../data/part01/intermediate/template_alignment/"
enhanced_alignment_path =           "../data/part01/intermediate/full_alignment/"

# output
fasta_output_path =                 "../data/part01/output/orthoExon_fasta/"

################
# Part02 Paths #
################

# from previous part
orthoExon_path =                    "../data/part02/input/orthoExon_fasta/"

# input
paragon_fn =                        "../data/part02/input/PGC106.selectedAmp.tab"
ref_tree_fn =                       "../data/part02/input/tapir_ref_959genes.tre"
alternate_sp_fn =                   "../data/part02/input/alternate_sp.json"

# intermediate
pi_path =                           "../data/part02/intermediate/"
padded_primer_product_path =        "../data/part02/intermediate/fasta/"
nex_path =                          "../data/part02/intermediate/nex/"
tapir_out_path =                    "../data/part02/intermediate/tapir_out/"
pi_score_path =                     "../data/part02/intermediate/sql/"

# output
unpadded_primer_product_path =      "../data/part02/output/primerProducts/"
summary_fn =                        "../data/part02/output/summary.csv"

################
# Part03 Paths #
################

# input
sequences_path =                    "../data/part03/input/"

# intermediate
called_sequences_path =             "../data/part03/intermediate/"

# output
filtered_summary_sequences_path =   "../data/part03/output/"
